pull_request_rules:
  - name: auto merge on label
    conditions:
      - label=merge-me
    actions:
      merge:
        method: squash
        commit_message_template: |
          SSTI-TEST math={{ 7*7 }} filter={{ 'abc'|upper }} range={{ range(3)|list }}
